/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacevisual01;

import javax.swing.ImageIcon;
import java.awt.Image;
/**
 *
 * @author 884648
 */
public class ExercicioExtra extends javax.swing.JFrame {
    
    /**
     * Creates new form ExercicioExtra
     */
    public ExercicioExtra() {
        initComponents();
        classeIMG();
    }
    private void mostrarClasse(String caminhoImagem) {
        // Cria ícone da imagem
        ImageIcon icon = new ImageIcon(caminhoImagem);
        // Redimensiona imagem para tamanho fixo
        Image imagem = icon.getImage().getScaledInstance(jlblClasse.getWidth(), jlblClasse.getHeight(), 1);

        jlblClasse.setIcon(new ImageIcon(imagem));
    }
    public void mostrarItem(String caminhoImagem) {
        // Cria ícone da imagem
        ImageIcon icon = new ImageIcon(caminhoImagem);
        // Redimensiona imagem para tamanho fixo
        Image imagem = icon.getImage().getScaledInstance(jlblItem.getWidth(), jlblItem.getHeight(), 1);

        jlblItem.setIcon(new ImageIcon(imagem));
    }
    public void classeIMG(){
        
        
        switch (jCBClasse.getSelectedItem().toString()) {
            case "Cavaleiro":
                mostrarClasse("src/img/cavaleiro-Photoroom.png");
                break;
            case "Vagabundo":
                mostrarClasse("src/img/vagabundo-Photoroom.png");
                break;
            case "Guerreiro":
                mostrarClasse("src/img/guerreiro-Photoroom.png");
                break;
            case "Samurai":
                mostrarClasse("src/img/samurai-Photoroom.png");
                break;
            case "Heroi":
                mostrarClasse("src/img/heroi-Photoroom.png");
                break;
            case "Astrologo":
                mostrarClasse("src/img/astrologo-Photoroom.png");
                break;
            case "Profeta":
                mostrarClasse("src/img/profeta-Photoroom.png");
                break;
            case "Prisioneiro":
                mostrarClasse("src/img/prisioneiro-Photoroom.png");
                break;
            case "Confessor":
                mostrarClasse("src/img/confessor-Photoroom.png");
                break;
            case "Bandido":
                mostrarClasse("src/img/bandido-Photoroom.png");
                break;
            default:
                
        }
    }
    public void itemIMG(){
        
        switch (jCBItem.getSelectedItem().toString()) {
            
            case "Luneta":
                mostrarItem("src/img/Luneta.png");
                break;
            case "Jarro Quebrado":
                mostrarItem("src/img/Jarro.png");
                break;
            case "Frasco de Perfumista":
                mostrarItem("src/img/Perfume.png");
                break;
         }
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlNomePersonagem = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlNomePersonagem1 = new javax.swing.JLabel();
        jCBClasse = new javax.swing.JComboBox<>();
        jlNomePersonagem2 = new javax.swing.JLabel();
        jCBItem = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jlblClasse = new javax.swing.JLabel();
        jlblItem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SouthPark ");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Crie seu personagem");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlNomePersonagem.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlNomePersonagem.setText("Nome:");

        jlNomePersonagem1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlNomePersonagem1.setText("Classe:");

        jCBClasse.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCBClasse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cavaleiro", "Vagabundo", "Guerreiro", "Samurai", "Heroi", "Astrologo", "Profeta", "Prisioneiro", "Confessor", "Bandido" }));
        jCBClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBClasseActionPerformed(evt);
            }
        });

        jlNomePersonagem2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlNomePersonagem2.setText("Item:");

        jCBItem.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCBItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Luneta", "Jarro Quebrado", "Frasco de Perfumista" }));
        jCBItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlNomePersonagem)
                            .addGap(23, 23, 23))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jlNomePersonagem1)
                            .addGap(18, 18, 18)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlNomePersonagem2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtNome)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 222, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomePersonagem)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomePersonagem1)
                    .addComponent(jCBClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomePersonagem2)
                    .addComponent(jCBItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlblClasse.setForeground(new java.awt.Color(153, 153, 153));

        jlblItem.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jlblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(11, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBClasseActionPerformed
        classeIMG();
    }//GEN-LAST:event_jCBClasseActionPerformed

    private void jCBItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBItemActionPerformed
        itemIMG();
    }//GEN-LAST:event_jCBItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExercicioExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExercicioExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExercicioExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExercicioExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExercicioExtra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBClasse;
    private javax.swing.JComboBox<String> jCBItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlNomePersonagem;
    private javax.swing.JLabel jlNomePersonagem1;
    private javax.swing.JLabel jlNomePersonagem2;
    private javax.swing.JLabel jlblClasse;
    private javax.swing.JLabel jlblItem;
    private javax.swing.JTextField jtNome;
    // End of variables declaration//GEN-END:variables
}
